/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cookie } from '../models/cookie';
export interface AuthenticationResponse {
  cookie?: Cookie;
  token?: string;
}
