/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Cookie {
  attributes?: {
[key: string]: string;
};
  /** @deprecated */comment?: string;
  domain?: string;
  httpOnly?: boolean;
  maxAge?: number;
  name?: string;
  path?: string;
  secure?: boolean;
  value?: string;
  /** @deprecated */version?: number;
}
